'use server';

/**
 * @fileOverview Generates intelligent follow-up questions during a mock interview based on the user's previous responses.
 *
 * - generateFollowUpQuestion - A function that generates a follow-up question.
 * - GenerateFollowUpQuestionInput - The input type for the generateFollowUpQuestion function.
 * - GenerateFollowUpQuestionOutput - The return type for the generateFollowUpQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFollowUpQuestionInputSchema = z.object({
  jobRole: z.string().describe('The job role for the mock interview.'),
  previousQuestion: z.string().describe('The previous interview question asked by the AI agent.'),
  userResponse: z.string().describe('The user\'s response to the previous question.'),
  interviewTranscript: z.string().describe('The full transcript of the interview so far.'),
});
export type GenerateFollowUpQuestionInput = z.infer<typeof GenerateFollowUpQuestionInputSchema>;

const GenerateFollowUpQuestionOutputSchema = z.object({
  followUpQuestion: z.string().describe('The intelligent follow-up question generated by the AI agent.'),
});
export type GenerateFollowUpQuestionOutput = z.infer<typeof GenerateFollowUpQuestionOutputSchema>;

export async function generateFollowUpQuestion(input: GenerateFollowUpQuestionInput): Promise<GenerateFollowUpQuestionOutput> {
  return generateFollowUpQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFollowUpQuestionPrompt',
  input: {schema: GenerateFollowUpQuestionInputSchema},
  output: {schema: GenerateFollowUpQuestionOutputSchema},
  prompt: `You are an AI interview agent designed to generate realistic follow-up questions during a mock interview.

The user is practicing for a {{jobRole}} interview. The previous question was: {{previousQuestion}}
The user\'s response was: {{userResponse}}

Here is the full transcript of the interview so far:
{{interviewTranscript}}

Based on the user\'s response and the interview transcript, generate an intelligent and relevant follow-up question.
The follow-up question should challenge the user and explore their skills and experience in more depth.

Follow Up Question: `,
});

const generateFollowUpQuestionFlow = ai.defineFlow(
  {
    name: 'generateFollowUpQuestionFlow',
    inputSchema: GenerateFollowUpQuestionInputSchema,
    outputSchema: GenerateFollowUpQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
